apiVersion: apps/v1
kind: Deployment
metadata:
  name: antonflux-deployment
  namespace: antonflux
spec:
  replicas: 2
  selector:
    matchLabels:
      app: antonfluxapp
  template:
    metadata:
      labels:
        app: antonfluxapp
    spec:
      containers:
      - name: antonfluxapp
        image: nginx
        ## this part is a bit tricky. hiding for now.
        ## volumeMounts:
        ##   - name: static-content
        ##     mountPath: /usr/share/nginx/html/
      ## this part is a bit tricky. hiding for now.
      ## volumes:
      ##   - name: static-content
      ##     hostPath:
      ##       path: $STATIC_CONTENT_PATH
      ##       type: Directory
